-- This database must have the name TRADEProd_STG

USE [TRADEProd_STG]
GO

CREATE TABLE [ARTICULOS_STG](
	[CODIGO_PRODUCTO] [nvarchar](255) NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[FAMILIA] [nvarchar](255) NULL,
	[PRECIO_UNITARIO] [int] NULL,
	[COSTO_UNITARIO] [int] NULL
) ON [PRIMARY]
GO

CREATE TABLE [CLIENTES_STG](
	[NRO] [smallint] NULL,
	[ID_CLIENTE] [nvarchar](255) NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[APELLIDO] [nvarchar](255) NULL,
	[EDAD] [smallint] NULL,
	[ESTADO_CIVIL] [nvarchar](255) NULL,
	[RESIDENCIA] [nvarchar](255) NULL,
	[ORIGEN] [nvarchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [COMUNA_STG](
	[COMUNA_ID] [smallint] NOT NULL,
	[COMUNA_NOMBRE] [nvarchar](255) NULL,
	[PROVINCIA_ID] [smallint] NULL
) ON [PRIMARY]
GO

CREATE TABLE [DETALLE_VENTA_STG](
	[DOCUMENTO] [nvarchar](255) NULL,
	[CODIGO_PRODUCTO] [nvarchar](255) NULL,
	[PRECIO_UNITARIO] [int] NULL,
	[CANTIDAD] [int] NULL,
	[TOTAL] [int] NULL
) ON [PRIMARY]
GO

CREATE TABLE [PROVINCIA_STG](
	[PROVINCIA_ID] [smallint] NOT NULL,
	[PROVINCIA_NOMBRE] [nvarchar](255) NULL,
	[REGION_ID] [smallint] NULL
) ON [PRIMARY]
GO

CREATE TABLE [REGION_STG](
	[REGION_ID] [smallint] NOT NULL,
	[REGION] [nvarchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [SUCURSAL_STG](
	[SUCURSAL_ID] [smallint] NOT NULL,
	[NOMBRE_SUCURSAL] [nvarchar](255) NULL,
	[COMUNA_ID] [smallint] NULL
) ON [PRIMARY]
GO

USE [TRADEProd_STG]
GO

CREATE TABLE [VENDEDORES_STG](
	[ID_VENDEDOR] [smallint] NOT NULL,
	[Nombre] [nvarchar](255) NULL,
	[Apellido] [nvarchar](255) NULL,
	[TIPO_ CAPACITACION] [nvarchar](255) NULL,
	[HORAS_CAPACITACION] [smallint] NULL
) ON [PRIMARY]
GO

CREATE TABLE [VENTAS_STG](
	[DOCUMENTO] [nvarchar](255) NOT NULL,
	[FECHA] [datetime] NULL,
	[ID_CLIENTE] [nvarchar](255) NULL,
	[TIPO_DOCUMENTO] [nvarchar](255) NULL,
	[ID_VENDEDOR] [smallint] NULL,
	[TOTAL_NETO] [int] NULL,
	[IMPUESTO] [int] NULL,
	[TOTAL_DOCUMENTO] [int] NULL,
	[SUCURSAL_ID] [smallint] NULL
) ON [PRIMARY]
GO